name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install via npm
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Unit Tests
        run: npm test
