name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install via npm
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Unit Tests
        run: npm test

      - name: Build Styleguide
        run: npm run styleguide:build
